apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: observability
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: ecommerce
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names: ["ecommerce"]
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            regex: ecommerce-service
            action: keep
          - source_labels: [__meta_kubernetes_endpoint_port_name]
            regex: http
            action: keep
        metric_relabel_configs:
          - source_labels: [__name__, area]
            regex: jvm_memory_(used|max)_bytes;heap
            action: keep
          - source_labels: [__name__]
            regex: jvm_threads_live_threads|jvm_gc_pause_seconds_(count|sum|max)|http_server_requests_seconds_count
            action: keep
          - action: drop
            regex: .*
            source_labels: [__name__]
        metrics_path: /ecommerce-service/actuator/prometheus
      - job_name: product
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names: ["ecommerce"]
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            regex: product-service
            action: keep
          - source_labels: [__meta_kubernetes_endpoint_port_name]
            regex: http
            action: keep
        metric_relabel_configs:
          - source_labels: [__name__, area]
            regex: jvm_memory_(used|max)_bytes;heap
            action: keep
          - source_labels: [__name__]
            regex: jvm_threads_live_threads|jvm_gc_pause_seconds_(count|sum|max)|http_server_requests_seconds_count
            action: keep
          - action: drop
            regex: .*
            source_labels: [__name__]
        metrics_path: /product-service/actuator/prometheus
      - job_name: images
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names: ["ecommerce"]
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            regex: images-service
            action: keep
          - source_labels: [__meta_kubernetes_endpoint_port_name]
            regex: http
            action: keep
        metric_relabel_configs:
          - source_labels: [__name__, area]
            regex: jvm_memory_(used|max)_bytes;heap
            action: keep
          - source_labels: [__name__]
            regex: jvm_threads_live_threads|jvm_gc_pause_seconds_(count|sum|max)|http_server_requests_seconds_count
            action: keep
          - action: drop
            regex: .*
            source_labels: [__name__]
        metrics_path: /image-service/actuator/prometheus
